# Generated by Django 4.0.6 on 2022-07-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('AC', 'Action'), ('DR', 'Drama'), ('CM', 'Comedy'), ('RM', 'Romance'), ('TH', 'Thriller'), ('HR', 'Horror'), ('SF', 'SF'), ('FT', 'Fantasy')], max_length=50, verbose_name='장르'),
        ),
    ]
